image: debian:stable

before_script:
   - apt-get update
   - apt-get -y install cmake make g++ libboost-filesystem1.67-dev libgsl-dev liblapack-dev

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - bin/test_quaca
      - lib/
    expire_in: 1 hour

test:
  stage: test
  script:
    - mkdir -p build
    - cd build
    - ./../bin/test_quaca
