dist: bionic
language: cpp
branches:
  only:
    - master
addons:
  apt:
    packages:
    - cmake 
    - make 
    - g++ 
    - libboost-filesystem-dev 
    - libgsl-dev 
    - liblapack-dev 
    - libboost-program-options-dev

jobs:
  include:
    - stage: build and test
      script:
      - mkdir -p build
      - cd build
      - cmake ..
      - make
      - ./../bin/test_quaca_unit
      - ./../bin/test_quaca_integrated
